version: '3'
services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: hotel
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
  frontend:
    image: nginx
    volumes:
        - ./frontend/src:/usr/share/nginx/html
    ports:
      - "3000:80"
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mysqldb